# Generated by Django 6.0 on 2025-12-17 04:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_type', models.CharField(choices=[('booking', 'Booking Confirmation'), ('reminder', 'Reminder'), ('cancellation', 'Cancellation'), ('reschedule', 'Reschedule')], help_text='Type of notification', max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram')], help_text='Notification channel', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was sent')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', help_text='Delivery status', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.CharField(help_text='Telegram chat ID', max_length=50, unique=True)),
                ('username', models.CharField(blank=True, help_text='Telegram username', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is the Telegram link active?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
