# Generated by Django 6.0 on 2025-12-17 04:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date_of_birth', models.DateField(help_text="Patient's date of birth")),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender', max_length=10)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact name', max_length=100)),
                ('emergency_phone', models.CharField(blank=True, help_text='Emergency contact phone', max_length=15)),
                ('medical_history', models.TextField(blank=True, help_text='Brief medical history')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_date', models.DateField(help_text='Preferred date')),
                ('requested_time', models.TimeField(help_text='Preferred time')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('is_notified', models.BooleanField(default=False, help_text='Has the patient been notified of availability?')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='patients.patientprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_date', models.DateField(help_text='Appointment date')),
                ('start_time', models.TimeField(help_text='Start time')),
                ('end_time', models.TimeField(help_text='End time')),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Lab'), ('follow_up', 'Follow-up')], help_text='Type of service', max_length=50)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled')], default='booked', help_text='Appointment status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or reason')),
                ('appointment_id', models.CharField(editable=False, help_text='Unique appointment ID', max_length=20, unique=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patientprofile')),
            ],
            options={
                'unique_together': {('doctor', 'appointment_date', 'start_time')},
            },
        ),
    ]
